from __future__ import annotations

from models.tunnel_destination import TunnelDestination
from models.tunnel_user import TunnelUser


def _bool_ssh(value: bool) -> str:
    return "yes" if value else "no"


def render_user_sshd_config(user: TunnelUser, destinations: list[TunnelDestination]) -> str:
    lines = [
        f"# Generated by TunnelKeeper for user {user.username}",
        f"# Do not edit manually — changes will be overwritten.",
        "",
        f"Match User {user.username}",
        f"    AllowTcpForwarding {_bool_ssh(user.allow_tcp_forwarding)}",
        f"    PermitTTY {_bool_ssh(user.permit_tty)}",
        f"    X11Forwarding {_bool_ssh(user.x11_forwarding)}",
        f"    AllowAgentForwarding {_bool_ssh(user.allow_agent_forwarding)}",
    ]

    force_cmd = user.force_command.strip()
    if force_cmd:
        escaped = force_cmd.replace('"', '\\"')
        lines.append(f'    ForceCommand "{escaped}"')

    enabled_destinations = [d for d in destinations if d.enabled]
    for dest in enabled_destinations:
        lines.append(f"    PermitOpen {dest.host}:{dest.port}")

    lines.append("")
    return "\n".join(lines)
