#!/usr/bin/env bash
# Install TunnelKeeper as a systemd service (enable + start).
# Run from the project root:
#   sudo ./scripts/install-systemd-service.sh
# or: make install-service

set -euo pipefail

SERVICE_NAME="tunnelkeeper"
UNIT_PATH="/etc/systemd/system/${SERVICE_NAME}.service"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_UVICORN="${ROOT}/.venv/bin/uvicorn"
ENV_FILE="${ROOT}/.env"

if [[ "${EUID}" -ne 0 ]]; then
  echo "This script must run as root. Try: sudo $0" >&2
  exit 1
fi

if [[ ! -x "${VENV_UVICORN}" ]]; then
  echo "Missing ${VENV_UVICORN}" >&2
  echo "Run as $(logname 2>/dev/null || echo "your user"): cd ${ROOT} && make install" >&2
  exit 1
fi

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Warning: ${ENV_FILE} not found. Copy .env.example to .env and configure API_TOKEN." >&2
fi

APP_HOST="127.0.0.1"
APP_PORT="8090"
if [[ -f "${ENV_FILE}" ]]; then
  # shellcheck disable=SC1091
  set -a
  source "${ENV_FILE}"
  set +a
fi
APP_HOST="${APP_HOST:-127.0.0.1}"
APP_PORT="${APP_PORT:-8090}"

if [[ -f "${ENV_FILE}" ]] && [[ "${ENABLE_API:-false}" != "true" ]]; then
  echo "Warning: ENABLE_API is not true in .env — service will start but REST API may be disabled." >&2
fi

cat >"${UNIT_PATH}" <<EOF
# Generated by TunnelKeeper install-systemd-service.sh
# Project: ${ROOT}

[Unit]
Description=TunnelKeeper SSH tunnel management agent
After=network.target ssh.service
Wants=ssh.service

[Service]
Type=simple
User=root
WorkingDirectory=${ROOT}
EnvironmentFile=${ENV_FILE}
ExecStart=${VENV_UVICORN} app.main:app --host ${APP_HOST} --port ${APP_PORT}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

chmod 644 "${UNIT_PATH}"
systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"
systemctl restart "${SERVICE_NAME}"

echo ""
echo "================================================"
echo "TunnelKeeper systemd service installed"
echo "================================================"
echo "Unit file:  ${UNIT_PATH}"
echo "Project:    ${ROOT}"
echo "Bind:       http://${APP_HOST}:${APP_PORT}"
echo "Status:     $(systemctl is-active "${SERVICE_NAME}" 2>/dev/null || echo unknown)"
echo ""
echo "Useful commands:"
echo "  sudo systemctl status ${SERVICE_NAME}"
echo "  sudo systemctl restart ${SERVICE_NAME}"
echo "  sudo systemctl stop ${SERVICE_NAME}"
echo "  sudo journalctl -u ${SERVICE_NAME} -f"
echo "================================================"
